### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [Slushnas/bwa-u4-feature-request#1]
Great idea to save and retrieve the search term after the app authorizes. Checking if the search term exists in `componentDIdMount` is the correct approach. There is also the option of running the authorization before a user is allowed to do a search. Use `localStorage.getItem` to store the data in the browser and `localStorage.removeItem` to remove the data. The technical design proposed is feasible and executable.

**Comment by Slushnas** [comment]
Thanks for the review. I think forcing the user to be authorized before making searches would be best but I didn't want to stray too far from the initial design for this feature.
